ALTER TABLE customers
ADD COLUMN IF NOT EXISTS line_uid VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE customers
ADD COLUMN IF NOT EXISTS line_name VARCHAR(100);

ALTER TABLE customers
ADD COLUMN IF NOT EXISTS email TEXT;