package errors

// Code generated by go generate; DO NOT EDIT.
// Source: errors.json

// Error codes constants for easy reference
const (
	// AUTH - auth related errors
	AuthContextMissing = "AuthContextMissing"
	AuthCustomerFailed = "AuthCustomerFailed"
	AuthInvalidCredentials = "AuthInvalidCredentials"
	AuthLineTokenExpired = "AuthLineTokenExpired"
	AuthLineTokenInvalid = "AuthLineTokenInvalid"
	AuthPermissionDenied = "AuthPermissionDenied"
	AuthRefreshTokenInvalid = "AuthRefreshTokenInvalid"
	AuthStaffFailed = "AuthStaffFailed"
	AuthTokenFormatError = "AuthTokenFormatError"
	AuthTokenInvalid = "AuthTokenInvalid"
	AuthTokenMissing = "AuthTokenMissing"

	// VAL - val related errors
	ValAllFieldsEmpty = "ValAllFieldsEmpty"
	ValFieldArrayMaxLength = "ValFieldArrayMaxLength"
	ValFieldArrayMinLength = "ValFieldArrayMinLength"
	ValFieldBoolean = "ValFieldBoolean"
	ValFieldDateFormat = "ValFieldDateFormat"
	ValFieldInvalidEmail = "ValFieldInvalidEmail"
	ValFieldMaxNumber = "ValFieldMaxNumber"
	ValFieldMinNumber = "ValFieldMinNumber"
	ValFieldNoBlank = "ValFieldNoBlank"
	ValFieldNumeric = "ValFieldNumeric"
	ValFieldOneof = "ValFieldOneof"
	ValFieldRequired = "ValFieldRequired"
	ValFieldStringMaxLength = "ValFieldStringMaxLength"
	ValFieldStringMinLength = "ValFieldStringMinLength"
	ValFieldTaiwanLandline = "ValFieldTaiwanLandline"
	ValFieldTaiwanMobile = "ValFieldTaiwanMobile"
	ValFieldTaiwanPhone = "ValFieldTaiwanPhone"
	ValFieldTimeFormat = "ValFieldTimeFormat"
	ValInputValidationFailed = "ValInputValidationFailed"
	ValJsonFormat = "ValJsonFormat"
	ValPathParamMissing = "ValPathParamMissing"
	ValTypeConversionFailed = "ValTypeConversionFailed"

	// BOOKING - booking related errors
	BookingInFutureNotAllowedToCheckout = "BookingInFutureNotAllowedToCheckout"
	BookingNotBelongToStore = "BookingNotBelongToStore"
	BookingNotFound = "BookingNotFound"
	BookingStatusNotAllowedToCancel = "BookingStatusNotAllowedToCancel"
	BookingStatusNotAllowedToUpdate = "BookingStatusNotAllowedToUpdate"
	BookingStatusNotCheckout = "BookingStatusNotCheckout"
	BookingTimeSlotNotFound = "BookingTimeSlotNotFound"
	BookingTimeSlotUnavailable = "BookingTimeSlotUnavailable"
	BookingUpdateIncomplete = "BookingUpdateIncomplete"

	// CUSTOMER - customer related errors
	CustomerAlreadyExists = "CustomerAlreadyExists"
	CustomerAuthNotFound = "CustomerAuthNotFound"
	CustomerIsBlacklisted = "CustomerIsBlacklisted"
	CustomerNotFound = "CustomerNotFound"

	// SCHEDULE - schedule related errors
	ScheduleAlreadyBookedDoNotDelete = "ScheduleAlreadyBookedDoNotDelete"
	ScheduleAlreadyBookedDoNotUpdateDate = "ScheduleAlreadyBookedDoNotUpdateDate"
	ScheduleAlreadyExists = "ScheduleAlreadyExists"
	ScheduleCannotCreateBeforeToday = "ScheduleCannotCreateBeforeToday"
	ScheduleDateRangeExceed31Days = "ScheduleDateRangeExceed31Days"
	ScheduleDuplicateWorkDateInput = "ScheduleDuplicateWorkDateInput"
	ScheduleEndBeforeStart = "ScheduleEndBeforeStart"
	ScheduleNotBelongToStore = "ScheduleNotBelongToStore"
	ScheduleNotBelongToStylist = "ScheduleNotBelongToStylist"
	ScheduleNotFound = "ScheduleNotFound"

	// SERVICE - service related errors
	ServiceAlreadyExists = "ServiceAlreadyExists"
	ServiceNotActive = "ServiceNotActive"
	ServiceNotAddon = "ServiceNotAddon"
	ServiceNotFound = "ServiceNotFound"
	ServiceNotMainService = "ServiceNotMainService"

	// STAFF - staff related errors
	StaffAlreadyExists = "StaffAlreadyExists"
	StaffInactive = "StaffInactive"
	StaffInvalidRole = "StaffInvalidRole"
	StaffNotFound = "StaffNotFound"
	StaffNotUpdateSelf = "StaffNotUpdateSelf"

	// STORE - store related errors
	StoreAlreadyExists = "StoreAlreadyExists"
	StoreNotActive = "StoreNotActive"
	StoreNotFound = "StoreNotFound"

	// STYLIST - stylist related errors
	StylistNotFound = "StylistNotFound"

	// TIME_SLOT - time slot related errors
	TimeSlotAlreadyBookedDoNotDelete = "TimeSlotAlreadyBookedDoNotDelete"
	TimeSlotAlreadyBookedDoNotUpdate = "TimeSlotAlreadyBookedDoNotUpdate"
	TimeSlotCannotUpdateSeparately = "TimeSlotCannotUpdateSeparately"
	TimeSlotConflict = "TimeSlotConflict"
	TimeSlotEndBeforeStart = "TimeSlotEndBeforeStart"
	TimeSlotNotBelongToSchedule = "TimeSlotNotBelongToSchedule"
	TimeSlotNotEnoughTime = "TimeSlotNotEnoughTime"
	TimeSlotNotFound = "TimeSlotNotFound"
	TimeSlotTemplateItemNotFound = "TimeSlotTemplateItemNotFound"
	TimeSlotTemplateNotFound = "TimeSlotTemplateNotFound"

	// SYS - sys related errors
	SysDatabaseError = "SysDatabaseError"
	SysInternalError = "SysInternalError"
	SysTimeout = "SysTimeout"

	// BOOKING_DETAIL - booking detail related errors
	BookingDetailNotFound = "BookingDetailNotFound"

	// BRAND - brand related errors
	BrandNameAlreadyExists = "BrandNameAlreadyExists"
	BrandNotFound = "BrandNotFound"

	// COUPON - coupon related errors
	CouponCodeAlreadyExists = "CouponCodeAlreadyExists"
	CouponDiscountExclusive = "CouponDiscountExclusive"
	CouponDiscountRequired = "CouponDiscountRequired"
	CouponNameAlreadyExists = "CouponNameAlreadyExists"
	CouponNotActive = "CouponNotActive"
	CouponNotFound = "CouponNotFound"

	// CUSTOMER_COUPON - customer coupon related errors
	CustomerCouponAlreadyUsed = "CustomerCouponAlreadyUsed"
	CustomerCouponExpired = "CustomerCouponExpired"
	CustomerCouponNotBelongToCustomer = "CustomerCouponNotBelongToCustomer"

	// EXPENSE - expense related errors
	ExpenseNotFound = "ExpenseNotFound"

	// PRODUCT - product related errors
	ProductNameBrandAlreadyExistsInStore = "ProductNameBrandAlreadyExistsInStore"
	ProductNotBelongToStore = "ProductNotBelongToStore"
	ProductNotFound = "ProductNotFound"
	ProductStockNotEnough = "ProductStockNotEnough"

	// PRODUCT_CATEGORY - product category related errors
	CategoryNameAlreadyExists = "CategoryNameAlreadyExists"
	CategoryNotFound = "CategoryNotFound"

	// REPORT - report related errors
	ReportDateRangeExceed1Year = "ReportDateRangeExceed1Year"

	// STOCK_USAGE - stock usage related errors
	StockUsageNotFound = "StockUsageNotFound"
	StockUsageNotInUse = "StockUsageNotInUse"

	// SUPPLIER - supplier related errors
	SupplierNameAlreadyExists = "SupplierNameAlreadyExists"
	SupplierNotFound = "SupplierNotFound"

)
