// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings
SET status = $2, cancel_reason = $3, updated_at = NOW()
WHERE id = $1 AND customer_id = $4
RETURNING id, status, cancel_reason, updated_at
`

type CancelBookingParams struct {
	ID           int64       `db:"id" json:"id"`
	Status       string      `db:"status" json:"status"`
	CancelReason pgtype.Text `db:"cancel_reason" json:"cancel_reason"`
	CustomerID   int64       `db:"customer_id" json:"customer_id"`
}

type CancelBookingRow struct {
	ID           int64              `db:"id" json:"id"`
	Status       string             `db:"status" json:"status"`
	CancelReason pgtype.Text        `db:"cancel_reason" json:"cancel_reason"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) (CancelBookingRow, error) {
	row := q.db.QueryRow(ctx, cancelBooking,
		arg.ID,
		arg.Status,
		arg.CancelReason,
		arg.CustomerID,
	)
	var i CancelBookingRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CancelReason,
		&i.UpdatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    id,
    store_id,
    customer_id,
    stylist_id,
    time_slot_id,
    is_chat_enabled,
    note,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, store_id, customer_id, stylist_id, time_slot_id, is_chat_enabled, actual_duration, note, used_products, status, created_at, updated_at, cancel_reason
`

type CreateBookingParams struct {
	ID            int64       `db:"id" json:"id"`
	StoreID       int64       `db:"store_id" json:"store_id"`
	CustomerID    int64       `db:"customer_id" json:"customer_id"`
	StylistID     int64       `db:"stylist_id" json:"stylist_id"`
	TimeSlotID    int64       `db:"time_slot_id" json:"time_slot_id"`
	IsChatEnabled pgtype.Bool `db:"is_chat_enabled" json:"is_chat_enabled"`
	Note          pgtype.Text `db:"note" json:"note"`
	Status        string      `db:"status" json:"status"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ID,
		arg.StoreID,
		arg.CustomerID,
		arg.StylistID,
		arg.TimeSlotID,
		arg.IsChatEnabled,
		arg.Note,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CustomerID,
		&i.StylistID,
		&i.TimeSlotID,
		&i.IsChatEnabled,
		&i.ActualDuration,
		&i.Note,
		&i.UsedProducts,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelReason,
	)
	return i, err
}

const deleteBookingDetailsByBookingID = `-- name: DeleteBookingDetailsByBookingID :exec
DELETE FROM booking_details
WHERE booking_id = $1
`

func (q *Queries) DeleteBookingDetailsByBookingID(ctx context.Context, bookingID int64) error {
	_, err := q.db.Exec(ctx, deleteBookingDetailsByBookingID, bookingID)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT
    b.id,
    b.store_id,
    s.name as store_name,
    b.customer_id,
    b.stylist_id,
    st.name as stylist_name,
    b.time_slot_id,
    ts.start_time,
    ts.end_time,
    sch.work_date,
    b.is_chat_enabled,
    b.note,
    b.status,
    b.created_at,
    b.updated_at
FROM bookings b
JOIN stores s ON b.store_id = s.id
JOIN stylists st ON b.stylist_id = st.id
JOIN time_slots ts ON b.time_slot_id = ts.id
JOIN schedules sch ON ts.schedule_id = sch.id
WHERE b.id = $1
`

type GetBookingByIDRow struct {
	ID            int64              `db:"id" json:"id"`
	StoreID       int64              `db:"store_id" json:"store_id"`
	StoreName     string             `db:"store_name" json:"store_name"`
	CustomerID    int64              `db:"customer_id" json:"customer_id"`
	StylistID     int64              `db:"stylist_id" json:"stylist_id"`
	StylistName   pgtype.Text        `db:"stylist_name" json:"stylist_name"`
	TimeSlotID    int64              `db:"time_slot_id" json:"time_slot_id"`
	StartTime     pgtype.Time        `db:"start_time" json:"start_time"`
	EndTime       pgtype.Time        `db:"end_time" json:"end_time"`
	WorkDate      pgtype.Date        `db:"work_date" json:"work_date"`
	IsChatEnabled pgtype.Bool        `db:"is_chat_enabled" json:"is_chat_enabled"`
	Note          pgtype.Text        `db:"note" json:"note"`
	Status        string             `db:"status" json:"status"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetBookingByID(ctx context.Context, id int64) (GetBookingByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.StoreName,
		&i.CustomerID,
		&i.StylistID,
		&i.StylistName,
		&i.TimeSlotID,
		&i.StartTime,
		&i.EndTime,
		&i.WorkDate,
		&i.IsChatEnabled,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingDetailsByBookingID = `-- name: GetBookingDetailsByBookingID :many
SELECT
    bd.id,
    bd.booking_id,
    bd.service_id,
    srv.name as service_name,
    bd.price,
    bd.created_at,
    srv.is_addon
FROM booking_details bd
JOIN services srv ON bd.service_id = srv.id
WHERE bd.booking_id = $1
ORDER BY srv.is_addon ASC, srv.name ASC
`

type GetBookingDetailsByBookingIDRow struct {
	ID          int64              `db:"id" json:"id"`
	BookingID   int64              `db:"booking_id" json:"booking_id"`
	ServiceID   int64              `db:"service_id" json:"service_id"`
	ServiceName string             `db:"service_name" json:"service_name"`
	Price       pgtype.Numeric     `db:"price" json:"price"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	IsAddon     pgtype.Bool        `db:"is_addon" json:"is_addon"`
}

func (q *Queries) GetBookingDetailsByBookingID(ctx context.Context, bookingID int64) ([]GetBookingDetailsByBookingIDRow, error) {
	rows, err := q.db.Query(ctx, getBookingDetailsByBookingID, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookingDetailsByBookingIDRow{}
	for rows.Next() {
		var i GetBookingDetailsByBookingIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.ServiceID,
			&i.ServiceName,
			&i.Price,
			&i.CreatedAt,
			&i.IsAddon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
