// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package dbgen

import (
	"context"
)

// iteratorForBatchCreateSchedules implements pgx.CopyFromSource.
type iteratorForBatchCreateSchedules struct {
	rows                 []BatchCreateSchedulesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateSchedules) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateSchedules) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].StoreID,
		r.rows[0].StylistID,
		r.rows[0].WorkDate,
		r.rows[0].Note,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForBatchCreateSchedules) Err() error {
	return nil
}

func (q *Queries) BatchCreateSchedules(ctx context.Context, arg []BatchCreateSchedulesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"schedules"}, []string{"id", "store_id", "stylist_id", "work_date", "note", "created_at", "updated_at"}, &iteratorForBatchCreateSchedules{rows: arg})
}

// iteratorForBatchCreateStaffUserStoreAccess implements pgx.CopyFromSource.
type iteratorForBatchCreateStaffUserStoreAccess struct {
	rows                 []BatchCreateStaffUserStoreAccessParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateStaffUserStoreAccess) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateStaffUserStoreAccess) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StoreID,
		r.rows[0].StaffUserID,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForBatchCreateStaffUserStoreAccess) Err() error {
	return nil
}

func (q *Queries) BatchCreateStaffUserStoreAccess(ctx context.Context, arg []BatchCreateStaffUserStoreAccessParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"staff_user_store_access"}, []string{"store_id", "staff_user_id", "created_at", "updated_at"}, &iteratorForBatchCreateStaffUserStoreAccess{rows: arg})
}

// iteratorForBatchCreateTimeSlotTemplateItems implements pgx.CopyFromSource.
type iteratorForBatchCreateTimeSlotTemplateItems struct {
	rows                 []BatchCreateTimeSlotTemplateItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateTimeSlotTemplateItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateTimeSlotTemplateItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].TemplateID,
		r.rows[0].StartTime,
		r.rows[0].EndTime,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForBatchCreateTimeSlotTemplateItems) Err() error {
	return nil
}

func (q *Queries) BatchCreateTimeSlotTemplateItems(ctx context.Context, arg []BatchCreateTimeSlotTemplateItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"time_slot_template_items"}, []string{"id", "template_id", "start_time", "end_time", "created_at", "updated_at"}, &iteratorForBatchCreateTimeSlotTemplateItems{rows: arg})
}

// iteratorForBatchCreateTimeSlots implements pgx.CopyFromSource.
type iteratorForBatchCreateTimeSlots struct {
	rows                 []BatchCreateTimeSlotsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateTimeSlots) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateTimeSlots) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ScheduleID,
		r.rows[0].StartTime,
		r.rows[0].EndTime,
		r.rows[0].IsAvailable,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForBatchCreateTimeSlots) Err() error {
	return nil
}

func (q *Queries) BatchCreateTimeSlots(ctx context.Context, arg []BatchCreateTimeSlotsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"time_slots"}, []string{"id", "schedule_id", "start_time", "end_time", "is_available", "created_at", "updated_at"}, &iteratorForBatchCreateTimeSlots{rows: arg})
}

// iteratorForCreateBookingDetails implements pgx.CopyFromSource.
type iteratorForCreateBookingDetails struct {
	rows                 []CreateBookingDetailsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBookingDetails) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBookingDetails) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].BookingID,
		r.rows[0].ServiceID,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForCreateBookingDetails) Err() error {
	return nil
}

func (q *Queries) CreateBookingDetails(ctx context.Context, arg []CreateBookingDetailsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"booking_details"}, []string{"id", "booking_id", "service_id", "created_at", "updated_at"}, &iteratorForCreateBookingDetails{rows: arg})
}
