// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: customer_coupon.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerCoupon = `-- name: CreateCustomerCoupon :exec
INSERT INTO customer_coupons (
  id,
  customer_id,
  coupon_id,
  valid_from,
  valid_to
) VALUES (
  $1, $2, $3, $4, $5
)
`

type CreateCustomerCouponParams struct {
	ID         int64              `db:"id" json:"id"`
	CustomerID int64              `db:"customer_id" json:"customer_id"`
	CouponID   int64              `db:"coupon_id" json:"coupon_id"`
	ValidFrom  pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidTo    pgtype.Timestamptz `db:"valid_to" json:"valid_to"`
}

func (q *Queries) CreateCustomerCoupon(ctx context.Context, arg CreateCustomerCouponParams) error {
	_, err := q.db.Exec(ctx, createCustomerCoupon,
		arg.ID,
		arg.CustomerID,
		arg.CouponID,
		arg.ValidFrom,
		arg.ValidTo,
	)
	return err
}
