// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: expense_item.sql

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BatchCreateExpenseItemsParams struct {
	ID              int64              `db:"id" json:"id"`
	ExpenseID       int64              `db:"expense_id" json:"expense_id"`
	ProductID       int64              `db:"product_id" json:"product_id"`
	Quantity        int32              `db:"quantity" json:"quantity"`
	TotalPrice      pgtype.Numeric     `db:"total_price" json:"total_price"`
	ExpirationDate  pgtype.Date        `db:"expiration_date" json:"expiration_date"`
	IsArrived       pgtype.Bool        `db:"is_arrived" json:"is_arrived"`
	ArrivalDate     pgtype.Date        `db:"arrival_date" json:"arrival_date"`
	StorageLocation pgtype.Text        `db:"storage_location" json:"storage_location"`
	Note            pgtype.Text        `db:"note" json:"note"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
