// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64              `db:"id" json:"id"`
	StoreID   int64              `db:"store_id" json:"store_id"`
	Name      string             `db:"name" json:"name"`
	Note      pgtype.Text        `db:"note" json:"note"`
	IsActive  pgtype.Bool        `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AccountTransaction struct {
	ID              int64              `db:"id" json:"id"`
	AccountID       int64              `db:"account_id" json:"account_id"`
	TransactionDate pgtype.Timestamptz `db:"transaction_date" json:"transaction_date"`
	Type            string             `db:"type" json:"type"`
	Amount          pgtype.Numeric     `db:"amount" json:"amount"`
	Balance         pgtype.Numeric     `db:"balance" json:"balance"`
	Note            pgtype.Text        `db:"note" json:"note"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Booking struct {
	ID             int64              `db:"id" json:"id"`
	StoreID        int64              `db:"store_id" json:"store_id"`
	CustomerID     int64              `db:"customer_id" json:"customer_id"`
	StylistID      int64              `db:"stylist_id" json:"stylist_id"`
	TimeSlotID     int64              `db:"time_slot_id" json:"time_slot_id"`
	IsChatEnabled  pgtype.Bool        `db:"is_chat_enabled" json:"is_chat_enabled"`
	ActualDuration pgtype.Int4        `db:"actual_duration" json:"actual_duration"`
	Note           pgtype.Text        `db:"note" json:"note"`
	UsedProducts   []string           `db:"used_products" json:"used_products"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CancelReason   pgtype.Text        `db:"cancel_reason" json:"cancel_reason"`
}

type BookingDetail struct {
	ID             int64              `db:"id" json:"id"`
	BookingID      int64              `db:"booking_id" json:"booking_id"`
	ServiceID      int64              `db:"service_id" json:"service_id"`
	Price          pgtype.Numeric     `db:"price" json:"price"`
	DiscountRate   pgtype.Numeric     `db:"discount_rate" json:"discount_rate"`
	DiscountAmount pgtype.Numeric     `db:"discount_amount" json:"discount_amount"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Brand struct {
	ID        int64              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	IsActive  pgtype.Bool        `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Checkout struct {
	ID            int64              `db:"id" json:"id"`
	BookingID     int64              `db:"booking_id" json:"booking_id"`
	TotalAmount   pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	FinalAmount   pgtype.Numeric     `db:"final_amount" json:"final_amount"`
	PaidAmount    pgtype.Numeric     `db:"paid_amount" json:"paid_amount"`
	PaymentMethod string             `db:"payment_method" json:"payment_method"`
	CouponID      pgtype.Int8        `db:"coupon_id" json:"coupon_id"`
	CheckoutUser  pgtype.Int8        `db:"checkout_user" json:"checkout_user"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Coupon struct {
	ID             int64              `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	Code           string             `db:"code" json:"code"`
	DiscountRate   pgtype.Numeric     `db:"discount_rate" json:"discount_rate"`
	DiscountAmount pgtype.Numeric     `db:"discount_amount" json:"discount_amount"`
	IsActive       pgtype.Bool        `db:"is_active" json:"is_active"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Customer struct {
	ID             int64              `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	Phone          string             `db:"phone" json:"phone"`
	Birthday       pgtype.Date        `db:"birthday" json:"birthday"`
	City           pgtype.Text        `db:"city" json:"city"`
	FavoriteShapes []string           `db:"favorite_shapes" json:"favorite_shapes"`
	FavoriteColors []string           `db:"favorite_colors" json:"favorite_colors"`
	FavoriteStyles []string           `db:"favorite_styles" json:"favorite_styles"`
	IsIntrovert    pgtype.Bool        `db:"is_introvert" json:"is_introvert"`
	ReferralSource []string           `db:"referral_source" json:"referral_source"`
	Referrer       pgtype.Text        `db:"referrer" json:"referrer"`
	CustomerNote   pgtype.Text        `db:"customer_note" json:"customer_note"`
	StoreNote      pgtype.Text        `db:"store_note" json:"store_note"`
	Level          pgtype.Text        `db:"level" json:"level"`
	IsBlacklisted  pgtype.Bool        `db:"is_blacklisted" json:"is_blacklisted"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastVisitAt    pgtype.Timestamptz `db:"last_visit_at" json:"last_visit_at"`
}

type CustomerAuth struct {
	ID          int64              `db:"id" json:"id"`
	CustomerID  int64              `db:"customer_id" json:"customer_id"`
	Provider    string             `db:"provider" json:"provider"`
	ProviderUid string             `db:"provider_uid" json:"provider_uid"`
	OtherInfo   []byte             `db:"other_info" json:"other_info"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CustomerCoupon struct {
	ID         int64              `db:"id" json:"id"`
	CustomerID int64              `db:"customer_id" json:"customer_id"`
	CouponID   int64              `db:"coupon_id" json:"coupon_id"`
	ValidFrom  pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidTo    pgtype.Timestamptz `db:"valid_to" json:"valid_to"`
	IsUsed     pgtype.Bool        `db:"is_used" json:"is_used"`
	UsedAt     pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CustomerToken struct {
	ID           int64              `db:"id" json:"id"`
	CustomerID   int64              `db:"customer_id" json:"customer_id"`
	RefreshToken string             `db:"refresh_token" json:"refresh_token"`
	UserAgent    pgtype.Text        `db:"user_agent" json:"user_agent"`
	IpAddress    *netip.Addr        `db:"ip_address" json:"ip_address"`
	ExpiredAt    pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	IsRevoked    pgtype.Bool        `db:"is_revoked" json:"is_revoked"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Expense struct {
	ID           int64              `db:"id" json:"id"`
	StoreID      int64              `db:"store_id" json:"store_id"`
	Category     pgtype.Text        `db:"category" json:"category"`
	SupplierID   int64              `db:"supplier_id" json:"supplier_id"`
	Amount       pgtype.Numeric     `db:"amount" json:"amount"`
	ExpenseDate  pgtype.Date        `db:"expense_date" json:"expense_date"`
	Note         pgtype.Text        `db:"note" json:"note"`
	PayerID      pgtype.Int8        `db:"payer_id" json:"payer_id"`
	IsReimbursed pgtype.Bool        `db:"is_reimbursed" json:"is_reimbursed"`
	ReimbursedAt pgtype.Timestamptz `db:"reimbursed_at" json:"reimbursed_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ExpenseItem struct {
	ID              int64              `db:"id" json:"id"`
	ExpenseID       int64              `db:"expense_id" json:"expense_id"`
	ProductID       int64              `db:"product_id" json:"product_id"`
	Quantity        int32              `db:"quantity" json:"quantity"`
	TotalPrice      pgtype.Numeric     `db:"total_price" json:"total_price"`
	ExpirationDate  pgtype.Date        `db:"expiration_date" json:"expiration_date"`
	IsArrived       pgtype.Bool        `db:"is_arrived" json:"is_arrived"`
	ArrivalDate     pgtype.Date        `db:"arrival_date" json:"arrival_date"`
	StorageLocation pgtype.Text        `db:"storage_location" json:"storage_location"`
	Note            pgtype.Text        `db:"note" json:"note"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Product struct {
	ID              int64              `db:"id" json:"id"`
	StoreID         int64              `db:"store_id" json:"store_id"`
	Name            string             `db:"name" json:"name"`
	BrandID         int64              `db:"brand_id" json:"brand_id"`
	CategoryID      int64              `db:"category_id" json:"category_id"`
	CurrentStock    int32              `db:"current_stock" json:"current_stock"`
	SafetyStock     pgtype.Int4        `db:"safety_stock" json:"safety_stock"`
	Unit            pgtype.Text        `db:"unit" json:"unit"`
	StorageLocation pgtype.Text        `db:"storage_location" json:"storage_location"`
	Note            pgtype.Text        `db:"note" json:"note"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProductCategory struct {
	ID        int64              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	IsActive  pgtype.Bool        `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Schedule struct {
	ID        int64              `db:"id" json:"id"`
	StoreID   int64              `db:"store_id" json:"store_id"`
	StylistID int64              `db:"stylist_id" json:"stylist_id"`
	WorkDate  pgtype.Date        `db:"work_date" json:"work_date"`
	Note      pgtype.Text        `db:"note" json:"note"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Service struct {
	ID              int64              `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	DurationMinutes int32              `db:"duration_minutes" json:"duration_minutes"`
	IsAddon         pgtype.Bool        `db:"is_addon" json:"is_addon"`
	IsVisible       pgtype.Bool        `db:"is_visible" json:"is_visible"`
	IsActive        pgtype.Bool        `db:"is_active" json:"is_active"`
	Note            pgtype.Text        `db:"note" json:"note"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type StaffUser struct {
	ID           int64              `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Role         string             `db:"role" json:"role"`
	IsActive     pgtype.Bool        `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type StaffUserStoreAccess struct {
	StoreID     int64              `db:"store_id" json:"store_id"`
	StaffUserID int64              `db:"staff_user_id" json:"staff_user_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type StaffUserToken struct {
	ID           int64              `db:"id" json:"id"`
	StaffUserID  int64              `db:"staff_user_id" json:"staff_user_id"`
	RefreshToken string             `db:"refresh_token" json:"refresh_token"`
	UserAgent    pgtype.Text        `db:"user_agent" json:"user_agent"`
	IpAddress    *netip.Addr        `db:"ip_address" json:"ip_address"`
	ExpiredAt    pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	IsRevoked    pgtype.Bool        `db:"is_revoked" json:"is_revoked"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type StockUsage struct {
	ID           int64              `db:"id" json:"id"`
	ProductID    int64              `db:"product_id" json:"product_id"`
	Quantity     int32              `db:"quantity" json:"quantity"`
	IsInUse      pgtype.Bool        `db:"is_in_use" json:"is_in_use"`
	Expiration   pgtype.Date        `db:"expiration" json:"expiration"`
	UsageStarted pgtype.Date        `db:"usage_started" json:"usage_started"`
	UsageEndedAt pgtype.Date        `db:"usage_ended_at" json:"usage_ended_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Store struct {
	ID        int64              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Address   pgtype.Text        `db:"address" json:"address"`
	Phone     pgtype.Text        `db:"phone" json:"phone"`
	IsActive  pgtype.Bool        `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Stylist struct {
	ID           int64              `db:"id" json:"id"`
	StaffUserID  int64              `db:"staff_user_id" json:"staff_user_id"`
	Name         pgtype.Text        `db:"name" json:"name"`
	GoodAtShapes []string           `db:"good_at_shapes" json:"good_at_shapes"`
	GoodAtColors []string           `db:"good_at_colors" json:"good_at_colors"`
	GoodAtStyles []string           `db:"good_at_styles" json:"good_at_styles"`
	IsIntrovert  pgtype.Bool        `db:"is_introvert" json:"is_introvert"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Supplier struct {
	ID        int64              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	IsActive  pgtype.Bool        `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TimeSlot struct {
	ID          int64              `db:"id" json:"id"`
	ScheduleID  int64              `db:"schedule_id" json:"schedule_id"`
	StartTime   pgtype.Time        `db:"start_time" json:"start_time"`
	EndTime     pgtype.Time        `db:"end_time" json:"end_time"`
	IsAvailable pgtype.Bool        `db:"is_available" json:"is_available"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TimeSlotTemplate struct {
	ID        int64              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Note      pgtype.Text        `db:"note" json:"note"`
	Updater   pgtype.Int8        `db:"updater" json:"updater"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TimeSlotTemplateItem struct {
	ID         int64              `db:"id" json:"id"`
	TemplateID int64              `db:"template_id" json:"template_id"`
	StartTime  pgtype.Time        `db:"start_time" json:"start_time"`
	EndTime    pgtype.Time        `db:"end_time" json:"end_time"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
