// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BatchCreateSchedules(ctx context.Context, arg []BatchCreateSchedulesParams) (int64, error)
	BatchCreateStaffUserStoreAccess(ctx context.Context, arg []BatchCreateStaffUserStoreAccessParams) (int64, error)
	BatchCreateTimeSlotTemplateItems(ctx context.Context, arg []BatchCreateTimeSlotTemplateItemsParams) (int64, error)
	BatchCreateTimeSlots(ctx context.Context, arg []BatchCreateTimeSlotsParams) (int64, error)
	CancelBooking(ctx context.Context, arg CancelBookingParams) (int64, error)
	CheckCustomerExistsByLineUid(ctx context.Context, lineUid string) (bool, error)
	CheckScheduleExists(ctx context.Context, arg CheckScheduleExistsParams) (bool, error)
	CheckScheduleExistsByID(ctx context.Context, id int64) (bool, error)
	CheckServiceNameExists(ctx context.Context, name string) (bool, error)
	CheckServiceNameExistsExcluding(ctx context.Context, arg CheckServiceNameExistsExcludingParams) (bool, error)
	CheckStaffUserExistsByUsername(ctx context.Context, username string) (bool, error)
	CheckStoreAccessExists(ctx context.Context, arg CheckStoreAccessExistsParams) (bool, error)
	CheckStoreExistAndActive(ctx context.Context, id int64) (bool, error)
	CheckStoreExistByID(ctx context.Context, id int64) (bool, error)
	CheckStoreNameExists(ctx context.Context, name string) (bool, error)
	CheckStoreNameExistsExcluding(ctx context.Context, arg CheckStoreNameExistsExcludingParams) (bool, error)
	CheckStoresExistAndActive(ctx context.Context, dollar_1 []int64) (CheckStoresExistAndActiveRow, error)
	CheckStylistExistAndActive(ctx context.Context, id int64) (bool, error)
	CheckTimeSlotOverlap(ctx context.Context, arg CheckTimeSlotOverlapParams) (bool, error)
	CheckTimeSlotOverlapExcluding(ctx context.Context, arg CheckTimeSlotOverlapExcludingParams) (bool, error)
	CheckTimeSlotTemplateExists(ctx context.Context, id int64) (bool, error)
	CheckTimeSlotTemplateItemExistsByIDAndTemplateID(ctx context.Context, arg CheckTimeSlotTemplateItemExistsByIDAndTemplateIDParams) (bool, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateBookingDetail(ctx context.Context, arg CreateBookingDetailParams) (BookingDetail, error)
	CreateBookingDetails(ctx context.Context, arg []CreateBookingDetailsParams) (int64, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) error
	CreateCustomerToken(ctx context.Context, arg CreateCustomerTokenParams) (CustomerToken, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (CreateStaffUserRow, error)
	CreateStaffUserStoreAccess(ctx context.Context, arg CreateStaffUserStoreAccessParams) error
	CreateStaffUserToken(ctx context.Context, arg CreateStaffUserTokenParams) (CreateStaffUserTokenRow, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (CreateStoreRow, error)
	CreateStylist(ctx context.Context, arg CreateStylistParams) (Stylist, error)
	CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (TimeSlot, error)
	CreateTimeSlotTemplate(ctx context.Context, arg CreateTimeSlotTemplateParams) (TimeSlotTemplate, error)
	CreateTimeSlotTemplateItem(ctx context.Context, arg CreateTimeSlotTemplateItemParams) (CreateTimeSlotTemplateItemRow, error)
	DeleteBookingDetailsByBookingID(ctx context.Context, bookingID int64) error
	DeleteSchedulesByIDs(ctx context.Context, dollar_1 []int64) error
	DeleteStaffUserStoreAccess(ctx context.Context, arg DeleteStaffUserStoreAccessParams) error
	DeleteTimeSlotByID(ctx context.Context, id int64) error
	DeleteTimeSlotTemplate(ctx context.Context, id int64) error
	DeleteTimeSlotTemplateItem(ctx context.Context, id int64) error
	ExistsCustomerByID(ctx context.Context, id int64) (bool, error)
	GetActiveStaffUserByUsername(ctx context.Context, username string) (StaffUser, error)
	GetActiveStylistNameByID(ctx context.Context, id int64) (pgtype.Text, error)
	GetAllActiveStoreAccessByStaffId(ctx context.Context, staffUserID int64) ([]GetAllActiveStoreAccessByStaffIdRow, error)
	GetAllActiveStoresName(ctx context.Context) ([]GetAllActiveStoresNameRow, error)
	GetAvailableSchedules(ctx context.Context, arg GetAvailableSchedulesParams) ([]GetAvailableSchedulesRow, error)
	GetAvailableTimeSlotsByScheduleID(ctx context.Context, scheduleID int64) ([]TimeSlot, error)
	GetBookingDetailByID(ctx context.Context, id int64) (GetBookingDetailByIDRow, error)
	GetBookingDetailsByBookingID(ctx context.Context, bookingID int64) ([]GetBookingDetailsByBookingIDRow, error)
	GetBookingDetailsByBookingIDs(ctx context.Context, dollar_1 []int64) ([]GetBookingDetailsByBookingIDsRow, error)
	GetCustomerByID(ctx context.Context, id int64) (GetCustomerByIDRow, error)
	GetCustomerByLineUid(ctx context.Context, lineUid string) (int64, error)
	GetScheduleByID(ctx context.Context, id int64) (Schedule, error)
	GetScheduleWithTimeSlotsByID(ctx context.Context, id int64) ([]GetScheduleWithTimeSlotsByIDRow, error)
	GetSchedulesWithTimeSlotsByIDs(ctx context.Context, dollar_1 []int64) ([]GetSchedulesWithTimeSlotsByIDsRow, error)
	GetServiceByID(ctx context.Context, id int64) (Service, error)
	GetServiceByIds(ctx context.Context, dollar_1 []int64) ([]GetServiceByIdsRow, error)
	GetStaffUserByID(ctx context.Context, id int64) (StaffUser, error)
	GetStoreByID(ctx context.Context, id int64) (GetStoreByIDRow, error)
	GetStoreDetailByID(ctx context.Context, id int64) (Store, error)
	GetStoresByIDs(ctx context.Context, dollar_1 []int64) ([]GetStoresByIDsRow, error)
	GetStylistByID(ctx context.Context, id int64) (Stylist, error)
	GetStylistByStaffUserID(ctx context.Context, staffUserID int64) (Stylist, error)
	GetTimeSlotByID(ctx context.Context, id int64) (TimeSlot, error)
	GetTimeSlotTemplateItemsByTemplateID(ctx context.Context, templateID int64) ([]GetTimeSlotTemplateItemsByTemplateIDRow, error)
	GetTimeSlotTemplateItemsByTemplateIDExcluding(ctx context.Context, arg GetTimeSlotTemplateItemsByTemplateIDExcludingParams) ([]GetTimeSlotTemplateItemsByTemplateIDExcludingRow, error)
	GetTimeSlotTemplateWithItemsByID(ctx context.Context, id int64) ([]GetTimeSlotTemplateWithItemsByIDRow, error)
	GetTimeSlotWithScheduleByID(ctx context.Context, id int64) (GetTimeSlotWithScheduleByIDRow, error)
	GetValidCustomerToken(ctx context.Context, refreshToken string) (GetValidCustomerTokenRow, error)
	GetValidStaffUserToken(ctx context.Context, refreshToken string) (GetValidStaffUserTokenRow, error)
	RevokeStaffUserToken(ctx context.Context, refreshToken string) error
	UpdateBookingByStaff(ctx context.Context, arg UpdateBookingByStaffParams) (int64, error)
	UpdateTimeSlot(ctx context.Context, arg UpdateTimeSlotParams) (int64, error)
	UpdateTimeSlotIsAvailable(ctx context.Context, arg UpdateTimeSlotIsAvailableParams) (int64, error)
	UpdateTimeSlotTemplateItem(ctx context.Context, arg UpdateTimeSlotTemplateItemParams) (UpdateTimeSlotTemplateItemRow, error)
}

var _ Querier = (*Queries)(nil)
