// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BatchCreateSchedules(ctx context.Context, arg []BatchCreateSchedulesParams) (int64, error)
	BatchCreateStaffUserStoreAccess(ctx context.Context, arg []BatchCreateStaffUserStoreAccessParams) (int64, error)
	BatchCreateTimeSlotTemplateItems(ctx context.Context, arg []BatchCreateTimeSlotTemplateItemsParams) (int64, error)
	BatchCreateTimeSlots(ctx context.Context, arg []BatchCreateTimeSlotsParams) (int64, error)
	BulkCreateBookingProducts(ctx context.Context, arg []BulkCreateBookingProductsParams) (int64, error)
	BulkDeleteBookingProducts(ctx context.Context, arg BulkDeleteBookingProductsParams) error
	CancelBooking(ctx context.Context, arg CancelBookingParams) (int64, error)
	CheckBrandExistByID(ctx context.Context, id int64) (bool, error)
	CheckBrandNameExists(ctx context.Context, name string) (bool, error)
	CheckBrandNameExistsExcludeSelf(ctx context.Context, arg CheckBrandNameExistsExcludeSelfParams) (bool, error)
	CheckCouponCodeExists(ctx context.Context, code string) (bool, error)
	CheckCouponExists(ctx context.Context, id int64) (bool, error)
	CheckCouponNameExists(ctx context.Context, name string) (bool, error)
	CheckCouponNameExistsExcluding(ctx context.Context, arg CheckCouponNameExistsExcludingParams) (bool, error)
	CheckCustomerExistsByID(ctx context.Context, id int64) (bool, error)
	CheckCustomerExistsByLineUid(ctx context.Context, lineUid string) (bool, error)
	CheckProductCategoryExistByID(ctx context.Context, id int64) (bool, error)
	CheckProductCategoryNameExists(ctx context.Context, name string) (bool, error)
	CheckProductCategoryNameExistsExcludeSelf(ctx context.Context, arg CheckProductCategoryNameExistsExcludeSelfParams) (bool, error)
	CheckProductNameBrandExistsInStore(ctx context.Context, arg CheckProductNameBrandExistsInStoreParams) (bool, error)
	CheckProductNameBrandExistsInStoreExcluding(ctx context.Context, arg CheckProductNameBrandExistsInStoreExcludingParams) (bool, error)
	CheckScheduleCanUpdateDate(ctx context.Context, scheduleID int64) (bool, error)
	CheckScheduleDateExists(ctx context.Context, arg CheckScheduleDateExistsParams) (bool, error)
	CheckScheduleExistsByID(ctx context.Context, id int64) (bool, error)
	CheckSchedulesCanDelete(ctx context.Context, dollar_1 []int64) ([]CheckSchedulesCanDeleteRow, error)
	CheckServiceNameExists(ctx context.Context, name string) (bool, error)
	CheckServiceNameExistsExcluding(ctx context.Context, arg CheckServiceNameExistsExcludingParams) (bool, error)
	CheckStaffUserExistsByUsername(ctx context.Context, username string) (bool, error)
	CheckStoreAccessExists(ctx context.Context, arg CheckStoreAccessExistsParams) (bool, error)
	CheckStoreExistAndActive(ctx context.Context, id int64) (bool, error)
	CheckStoreExistByID(ctx context.Context, id int64) (bool, error)
	CheckStoreNameExists(ctx context.Context, name string) (bool, error)
	CheckStoreNameExistsExcluding(ctx context.Context, arg CheckStoreNameExistsExcludingParams) (bool, error)
	CheckStoresExistAndActive(ctx context.Context, dollar_1 []int64) (CheckStoresExistAndActiveRow, error)
	CheckStylistExistAndActive(ctx context.Context, id int64) (bool, error)
	CheckTimeSlotOverlap(ctx context.Context, arg CheckTimeSlotOverlapParams) (bool, error)
	CheckTimeSlotOverlapExcluding(ctx context.Context, arg CheckTimeSlotOverlapExcludingParams) (bool, error)
	CheckTimeSlotTemplateExists(ctx context.Context, id int64) (bool, error)
	CheckTimeSlotTemplateItemExistsByIDAndTemplateID(ctx context.Context, arg CheckTimeSlotTemplateItemExistsByIDAndTemplateIDParams) (bool, error)
	CountBookingDetailsByIDsAndBookingID(ctx context.Context, arg CountBookingDetailsByIDsAndBookingIDParams) (int64, error)
	CountProductsByIDs(ctx context.Context, arg CountProductsByIDsParams) (int64, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateBookingDetails(ctx context.Context, arg []CreateBookingDetailsParams) (int64, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (int64, error)
	CreateCheckout(ctx context.Context, arg CreateCheckoutParams) error
	CreateCoupon(ctx context.Context, arg CreateCouponParams) error
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) error
	CreateCustomerCoupon(ctx context.Context, arg CreateCustomerCouponParams) error
	CreateCustomerToken(ctx context.Context, arg CreateCustomerTokenParams) (CustomerToken, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (int64, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (CreateStaffUserRow, error)
	CreateStaffUserStoreAccess(ctx context.Context, arg CreateStaffUserStoreAccessParams) error
	CreateStaffUserToken(ctx context.Context, arg CreateStaffUserTokenParams) (CreateStaffUserTokenRow, error)
	CreateStockUsage(ctx context.Context, arg CreateStockUsageParams) error
	CreateStore(ctx context.Context, arg CreateStoreParams) error
	CreateStylist(ctx context.Context, arg CreateStylistParams) (Stylist, error)
	CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (TimeSlot, error)
	CreateTimeSlotTemplate(ctx context.Context, arg CreateTimeSlotTemplateParams) (TimeSlotTemplate, error)
	CreateTimeSlotTemplateItem(ctx context.Context, arg CreateTimeSlotTemplateItemParams) (CreateTimeSlotTemplateItemRow, error)
	DeleteSchedulesByIDs(ctx context.Context, dollar_1 []int64) error
	DeleteStaffUserStoreAccess(ctx context.Context, arg DeleteStaffUserStoreAccessParams) error
	DeleteTimeSlotByID(ctx context.Context, id int64) error
	DeleteTimeSlotTemplate(ctx context.Context, id int64) error
	DeleteTimeSlotTemplateItem(ctx context.Context, id int64) error
	GetActiveStaffUserByUsername(ctx context.Context, username string) (StaffUser, error)
	GetActiveStylistNameByID(ctx context.Context, id int64) (pgtype.Text, error)
	GetAllActiveStoreAccessByStaffId(ctx context.Context, staffUserID int64) ([]GetAllActiveStoreAccessByStaffIdRow, error)
	GetAllActiveStoresName(ctx context.Context) ([]GetAllActiveStoresNameRow, error)
	GetAllBookingProductIdsByBookingID(ctx context.Context, bookingID int64) ([]int64, error)
	GetAvailableSchedules(ctx context.Context, arg GetAvailableSchedulesParams) ([]GetAvailableSchedulesRow, error)
	GetAvailableTimeSlotsByScheduleID(ctx context.Context, scheduleID int64) ([]TimeSlot, error)
	GetBookingDetailByID(ctx context.Context, id int64) (GetBookingDetailByIDRow, error)
	GetBookingDetailPriceByBookingIDs(ctx context.Context, dollar_1 []int64) ([]GetBookingDetailPriceByBookingIDsRow, error)
	GetBookingDetailsByBookingID(ctx context.Context, bookingID int64) ([]GetBookingDetailsByBookingIDRow, error)
	GetBookingDetailsByBookingIDs(ctx context.Context, dollar_1 []int64) ([]GetBookingDetailsByBookingIDsRow, error)
	GetBookingInfoWithDateByID(ctx context.Context, id int64) (GetBookingInfoWithDateByIDRow, error)
	GetCheckoutByBookingID(ctx context.Context, bookingID int64) (GetCheckoutByBookingIDRow, error)
	GetCouponByIDs(ctx context.Context, dollar_1 []int64) ([]GetCouponByIDsRow, error)
	GetCustomerByID(ctx context.Context, id int64) (GetCustomerByIDRow, error)
	GetCustomerByIDs(ctx context.Context, dollar_1 []int64) ([]GetCustomerByIDsRow, error)
	GetCustomerByLineUid(ctx context.Context, lineUid string) (GetCustomerByLineUidRow, error)
	GetCustomerCouponPriceInfoByID(ctx context.Context, id int64) (GetCustomerCouponPriceInfoByIDRow, error)
	GetProductByID(ctx context.Context, id int64) (GetProductByIDRow, error)
	GetScheduleByID(ctx context.Context, id int64) (GetScheduleByIDRow, error)
	GetScheduleWithTimeSlotsByID(ctx context.Context, id int64) ([]GetScheduleWithTimeSlotsByIDRow, error)
	GetServiceByID(ctx context.Context, id int64) (Service, error)
	GetServiceByIds(ctx context.Context, dollar_1 []int64) ([]GetServiceByIdsRow, error)
	GetStaffUserByID(ctx context.Context, id int64) (StaffUser, error)
	GetStockUsageByID(ctx context.Context, id int64) (StockUsage, error)
	GetStoreByID(ctx context.Context, id int64) (GetStoreByIDRow, error)
	GetStoreDetailByID(ctx context.Context, id int64) (Store, error)
	GetStorePerformanceGroupByStylist(ctx context.Context, arg GetStorePerformanceGroupByStylistParams) ([]GetStorePerformanceGroupByStylistRow, error)
	GetStylistByID(ctx context.Context, id int64) (Stylist, error)
	GetStylistByStaffUserID(ctx context.Context, staffUserID int64) (Stylist, error)
	GetStylistIDByStaffUserID(ctx context.Context, staffUserID int64) (int64, error)
	GetStylistPerformanceGroupByStore(ctx context.Context, arg GetStylistPerformanceGroupByStoreParams) ([]GetStylistPerformanceGroupByStoreRow, error)
	GetTimeSlotByID(ctx context.Context, id int64) (TimeSlot, error)
	GetTimeSlotTemplateItemsByTemplateID(ctx context.Context, templateID int64) ([]GetTimeSlotTemplateItemsByTemplateIDRow, error)
	GetTimeSlotTemplateItemsByTemplateIDExcluding(ctx context.Context, arg GetTimeSlotTemplateItemsByTemplateIDExcludingParams) ([]GetTimeSlotTemplateItemsByTemplateIDExcludingRow, error)
	GetTimeSlotTemplateWithItemsByID(ctx context.Context, id int64) ([]GetTimeSlotTemplateWithItemsByIDRow, error)
	GetTimeSlotWithScheduleByID(ctx context.Context, id int64) (GetTimeSlotWithScheduleByIDRow, error)
	GetValidCustomerToken(ctx context.Context, refreshToken string) (GetValidCustomerTokenRow, error)
	GetValidStaffUserToken(ctx context.Context, refreshToken string) (GetValidStaffUserTokenRow, error)
	RevokeStaffUserToken(ctx context.Context, refreshToken string) error
	UpdateBookingActualDuration(ctx context.Context, arg UpdateBookingActualDurationParams) error
	UpdateBookingDetailPriceInfo(ctx context.Context, arg UpdateBookingDetailPriceInfoParams) error
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error
	UpdateCustomerCouponUsed(ctx context.Context, id int64) error
	UpdateCustomerLineName(ctx context.Context, arg UpdateCustomerLineNameParams) error
	UpdateProductCurrentStock(ctx context.Context, arg UpdateProductCurrentStockParams) error
	UpdateStockUsageFinish(ctx context.Context, arg UpdateStockUsageFinishParams) error
	UpdateTimeSlot(ctx context.Context, arg UpdateTimeSlotParams) (int64, error)
	UpdateTimeSlotIsAvailable(ctx context.Context, arg UpdateTimeSlotIsAvailableParams) (int64, error)
	UpdateTimeSlotTemplateItem(ctx context.Context, arg UpdateTimeSlotTemplateItemParams) (UpdateTimeSlotTemplateItemRow, error)
}

var _ Querier = (*Queries)(nil)
