// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: staff_user.sql

package dbgen

import (
	"context"
)

const getStaffUserByUsername = `-- name: GetStaffUserByUsername :one
SELECT
    id,
    username,
    email,
    password_hash,
    role,
    is_active,
    created_at,
    updated_at
FROM staff_users
WHERE username = $1 AND is_active = true
`

func (q *Queries) GetStaffUserByUsername(ctx context.Context, username string) (StaffUser, error) {
	row := q.db.QueryRow(ctx, getStaffUserByUsername, username)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
