// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: staff_user_store_access.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchCreateStaffUserStoreAccessParams struct {
	StoreID     int64              `db:"store_id" json:"store_id"`
	StaffUserID int64              `db:"staff_user_id" json:"staff_user_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

const checkStoreAccessExists = `-- name: CheckStoreAccessExists :one
SELECT EXISTS(
    SELECT 1 FROM staff_user_store_access
    WHERE staff_user_id = $1 AND store_id = $2
) as exists
`

type CheckStoreAccessExistsParams struct {
	StaffUserID int64 `db:"staff_user_id" json:"staff_user_id"`
	StoreID     int64 `db:"store_id" json:"store_id"`
}

func (q *Queries) CheckStoreAccessExists(ctx context.Context, arg CheckStoreAccessExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkStoreAccessExists, arg.StaffUserID, arg.StoreID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createStaffUserStoreAccess = `-- name: CreateStaffUserStoreAccess :exec
INSERT INTO staff_user_store_access (
    store_id,
    staff_user_id,
    created_at,
    updated_at
) VALUES (
    $1, $2, NOW(), NOW()
)
`

type CreateStaffUserStoreAccessParams struct {
	StoreID     int64 `db:"store_id" json:"store_id"`
	StaffUserID int64 `db:"staff_user_id" json:"staff_user_id"`
}

func (q *Queries) CreateStaffUserStoreAccess(ctx context.Context, arg CreateStaffUserStoreAccessParams) error {
	_, err := q.db.Exec(ctx, createStaffUserStoreAccess, arg.StoreID, arg.StaffUserID)
	return err
}

const deleteStaffUserStoreAccess = `-- name: DeleteStaffUserStoreAccess :exec
DELETE FROM staff_user_store_access
WHERE staff_user_id = $1 AND store_id = ANY($2::bigint[])
`

type DeleteStaffUserStoreAccessParams struct {
	StaffUserID int64   `db:"staff_user_id" json:"staff_user_id"`
	Column2     []int64 `db:"column_2" json:"column_2"`
}

func (q *Queries) DeleteStaffUserStoreAccess(ctx context.Context, arg DeleteStaffUserStoreAccessParams) error {
	_, err := q.db.Exec(ctx, deleteStaffUserStoreAccess, arg.StaffUserID, arg.Column2)
	return err
}

const getAllActiveStoreAccessByStaffId = `-- name: GetAllActiveStoreAccessByStaffId :many
SELECT
    sa.store_id,
    s.name as store_name
FROM staff_user_store_access sa
JOIN stores s ON sa.store_id = s.id
WHERE sa.staff_user_id = $1 AND s.is_active = true
`

type GetAllActiveStoreAccessByStaffIdRow struct {
	StoreID   int64  `db:"store_id" json:"store_id"`
	StoreName string `db:"store_name" json:"store_name"`
}

func (q *Queries) GetAllActiveStoreAccessByStaffId(ctx context.Context, staffUserID int64) ([]GetAllActiveStoreAccessByStaffIdRow, error) {
	rows, err := q.db.Query(ctx, getAllActiveStoreAccessByStaffId, staffUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllActiveStoreAccessByStaffIdRow{}
	for rows.Next() {
		var i GetAllActiveStoreAccessByStaffIdRow
		if err := rows.Scan(&i.StoreID, &i.StoreName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
