// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stock_usages.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockUsage = `-- name: CreateStockUsage :exec
INSERT INTO stock_usages (
    id,
    product_id,
    quantity,
    expiration,
    usage_started
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateStockUsageParams struct {
	ID           int64       `db:"id" json:"id"`
	ProductID    int64       `db:"product_id" json:"product_id"`
	Quantity     int32       `db:"quantity" json:"quantity"`
	Expiration   pgtype.Date `db:"expiration" json:"expiration"`
	UsageStarted pgtype.Date `db:"usage_started" json:"usage_started"`
}

func (q *Queries) CreateStockUsage(ctx context.Context, arg CreateStockUsageParams) error {
	_, err := q.db.Exec(ctx, createStockUsage,
		arg.ID,
		arg.ProductID,
		arg.Quantity,
		arg.Expiration,
		arg.UsageStarted,
	)
	return err
}
