// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stock_usages.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockUsage = `-- name: CreateStockUsage :exec
INSERT INTO stock_usages (
    id,
    product_id,
    quantity,
    expiration,
    usage_started
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateStockUsageParams struct {
	ID           int64       `db:"id" json:"id"`
	ProductID    int64       `db:"product_id" json:"product_id"`
	Quantity     int32       `db:"quantity" json:"quantity"`
	Expiration   pgtype.Date `db:"expiration" json:"expiration"`
	UsageStarted pgtype.Date `db:"usage_started" json:"usage_started"`
}

func (q *Queries) CreateStockUsage(ctx context.Context, arg CreateStockUsageParams) error {
	_, err := q.db.Exec(ctx, createStockUsage,
		arg.ID,
		arg.ProductID,
		arg.Quantity,
		arg.Expiration,
		arg.UsageStarted,
	)
	return err
}

const getStockUsageByID = `-- name: GetStockUsageByID :one
SELECT
    id,
    product_id,
    quantity,
    is_in_use,
    expiration,
    usage_started,
    usage_ended_at,
    created_at,
    updated_at
FROM stock_usages
WHERE id = $1
`

func (q *Queries) GetStockUsageByID(ctx context.Context, id int64) (StockUsage, error) {
	row := q.db.QueryRow(ctx, getStockUsageByID, id)
	var i StockUsage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Quantity,
		&i.IsInUse,
		&i.Expiration,
		&i.UsageStarted,
		&i.UsageEndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStockUsageFinish = `-- name: UpdateStockUsageFinish :exec
UPDATE stock_usages
SET 
    is_in_use = false,
    usage_ended_at = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateStockUsageFinishParams struct {
	ID           int64       `db:"id" json:"id"`
	UsageEndedAt pgtype.Date `db:"usage_ended_at" json:"usage_ended_at"`
}

func (q *Queries) UpdateStockUsageFinish(ctx context.Context, arg UpdateStockUsageFinishParams) error {
	_, err := q.db.Exec(ctx, updateStockUsageFinish, arg.ID, arg.UsageEndedAt)
	return err
}
