// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: time_slot_template.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchCreateTimeSlotTemplateItemsParams struct {
	ID         int64              `db:"id" json:"id"`
	TemplateID int64              `db:"template_id" json:"template_id"`
	StartTime  pgtype.Time        `db:"start_time" json:"start_time"`
	EndTime    pgtype.Time        `db:"end_time" json:"end_time"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

const createTimeSlotTemplate = `-- name: CreateTimeSlotTemplate :one
INSERT INTO time_slot_templates (
    id,
    name,
    note,
    updater,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
) RETURNING
    id,
    name,
    note,
    updater,
    created_at,
    updated_at
`

type CreateTimeSlotTemplateParams struct {
	ID      int64       `db:"id" json:"id"`
	Name    string      `db:"name" json:"name"`
	Note    pgtype.Text `db:"note" json:"note"`
	Updater pgtype.Int8 `db:"updater" json:"updater"`
}

func (q *Queries) CreateTimeSlotTemplate(ctx context.Context, arg CreateTimeSlotTemplateParams) (TimeSlotTemplate, error) {
	row := q.db.QueryRow(ctx, createTimeSlotTemplate,
		arg.ID,
		arg.Name,
		arg.Note,
		arg.Updater,
	)
	var i TimeSlotTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Note,
		&i.Updater,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimeSlotTemplateByID = `-- name: GetTimeSlotTemplateByID :one
SELECT
    id,
    name,
    note,
    updater,
    created_at,
    updated_at
FROM time_slot_templates
WHERE id = $1
`

func (q *Queries) GetTimeSlotTemplateByID(ctx context.Context, id int64) (TimeSlotTemplate, error) {
	row := q.db.QueryRow(ctx, getTimeSlotTemplateByID, id)
	var i TimeSlotTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Note,
		&i.Updater,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimeSlotTemplateItemsByTemplateID = `-- name: GetTimeSlotTemplateItemsByTemplateID :many
SELECT
    id,
    template_id,
    start_time,
    end_time,
    created_at,
    updated_at
FROM time_slot_template_items
WHERE template_id = $1
ORDER BY start_time
`

func (q *Queries) GetTimeSlotTemplateItemsByTemplateID(ctx context.Context, templateID int64) ([]TimeSlotTemplateItem, error) {
	rows, err := q.db.Query(ctx, getTimeSlotTemplateItemsByTemplateID, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeSlotTemplateItem{}
	for rows.Next() {
		var i TimeSlotTemplateItem
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
