// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: time_slot_template_items.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchCreateTimeSlotTemplateItemsParams struct {
	ID         int64              `db:"id" json:"id"`
	TemplateID int64              `db:"template_id" json:"template_id"`
	StartTime  pgtype.Time        `db:"start_time" json:"start_time"`
	EndTime    pgtype.Time        `db:"end_time" json:"end_time"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

const checkTimeSlotTemplateItemExistsByIDAndTemplateID = `-- name: CheckTimeSlotTemplateItemExistsByIDAndTemplateID :one
SELECT EXISTS (
    SELECT 1
    FROM time_slot_template_items
    WHERE id = $1 AND template_id = $2
)
`

type CheckTimeSlotTemplateItemExistsByIDAndTemplateIDParams struct {
	ID         int64 `db:"id" json:"id"`
	TemplateID int64 `db:"template_id" json:"template_id"`
}

func (q *Queries) CheckTimeSlotTemplateItemExistsByIDAndTemplateID(ctx context.Context, arg CheckTimeSlotTemplateItemExistsByIDAndTemplateIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTimeSlotTemplateItemExistsByIDAndTemplateID, arg.ID, arg.TemplateID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createTimeSlotTemplateItem = `-- name: CreateTimeSlotTemplateItem :one
INSERT INTO time_slot_template_items (
    id,
    template_id,
    start_time,
    end_time,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
) RETURNING
    id,
    template_id,
    start_time,
    end_time
`

type CreateTimeSlotTemplateItemParams struct {
	ID         int64       `db:"id" json:"id"`
	TemplateID int64       `db:"template_id" json:"template_id"`
	StartTime  pgtype.Time `db:"start_time" json:"start_time"`
	EndTime    pgtype.Time `db:"end_time" json:"end_time"`
}

type CreateTimeSlotTemplateItemRow struct {
	ID         int64       `db:"id" json:"id"`
	TemplateID int64       `db:"template_id" json:"template_id"`
	StartTime  pgtype.Time `db:"start_time" json:"start_time"`
	EndTime    pgtype.Time `db:"end_time" json:"end_time"`
}

func (q *Queries) CreateTimeSlotTemplateItem(ctx context.Context, arg CreateTimeSlotTemplateItemParams) (CreateTimeSlotTemplateItemRow, error) {
	row := q.db.QueryRow(ctx, createTimeSlotTemplateItem,
		arg.ID,
		arg.TemplateID,
		arg.StartTime,
		arg.EndTime,
	)
	var i CreateTimeSlotTemplateItemRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteTimeSlotTemplateItem = `-- name: DeleteTimeSlotTemplateItem :exec
DELETE FROM time_slot_template_items
WHERE id = $1
`

func (q *Queries) DeleteTimeSlotTemplateItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTimeSlotTemplateItem, id)
	return err
}

const getTimeSlotTemplateItemsByTemplateID = `-- name: GetTimeSlotTemplateItemsByTemplateID :many
SELECT
    start_time,
    end_time
FROM time_slot_template_items
WHERE template_id = $1
ORDER BY start_time
`

type GetTimeSlotTemplateItemsByTemplateIDRow struct {
	StartTime pgtype.Time `db:"start_time" json:"start_time"`
	EndTime   pgtype.Time `db:"end_time" json:"end_time"`
}

func (q *Queries) GetTimeSlotTemplateItemsByTemplateID(ctx context.Context, templateID int64) ([]GetTimeSlotTemplateItemsByTemplateIDRow, error) {
	rows, err := q.db.Query(ctx, getTimeSlotTemplateItemsByTemplateID, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTimeSlotTemplateItemsByTemplateIDRow{}
	for rows.Next() {
		var i GetTimeSlotTemplateItemsByTemplateIDRow
		if err := rows.Scan(&i.StartTime, &i.EndTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeSlotTemplateItemsByTemplateIDExcluding = `-- name: GetTimeSlotTemplateItemsByTemplateIDExcluding :many
SELECT id, template_id, start_time, end_time
FROM time_slot_template_items
WHERE template_id = $1 AND id != $2
`

type GetTimeSlotTemplateItemsByTemplateIDExcludingParams struct {
	TemplateID int64 `db:"template_id" json:"template_id"`
	ID         int64 `db:"id" json:"id"`
}

type GetTimeSlotTemplateItemsByTemplateIDExcludingRow struct {
	ID         int64       `db:"id" json:"id"`
	TemplateID int64       `db:"template_id" json:"template_id"`
	StartTime  pgtype.Time `db:"start_time" json:"start_time"`
	EndTime    pgtype.Time `db:"end_time" json:"end_time"`
}

func (q *Queries) GetTimeSlotTemplateItemsByTemplateIDExcluding(ctx context.Context, arg GetTimeSlotTemplateItemsByTemplateIDExcludingParams) ([]GetTimeSlotTemplateItemsByTemplateIDExcludingRow, error) {
	rows, err := q.db.Query(ctx, getTimeSlotTemplateItemsByTemplateIDExcluding, arg.TemplateID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTimeSlotTemplateItemsByTemplateIDExcludingRow{}
	for rows.Next() {
		var i GetTimeSlotTemplateItemsByTemplateIDExcludingRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeSlotTemplateItem = `-- name: UpdateTimeSlotTemplateItem :one
UPDATE time_slot_template_items
SET
    start_time = $2,
    end_time = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, template_id, start_time, end_time
`

type UpdateTimeSlotTemplateItemParams struct {
	ID        int64       `db:"id" json:"id"`
	StartTime pgtype.Time `db:"start_time" json:"start_time"`
	EndTime   pgtype.Time `db:"end_time" json:"end_time"`
}

type UpdateTimeSlotTemplateItemRow struct {
	ID         int64       `db:"id" json:"id"`
	TemplateID int64       `db:"template_id" json:"template_id"`
	StartTime  pgtype.Time `db:"start_time" json:"start_time"`
	EndTime    pgtype.Time `db:"end_time" json:"end_time"`
}

func (q *Queries) UpdateTimeSlotTemplateItem(ctx context.Context, arg UpdateTimeSlotTemplateItemParams) (UpdateTimeSlotTemplateItemRow, error) {
	row := q.db.QueryRow(ctx, updateTimeSlotTemplateItem, arg.ID, arg.StartTime, arg.EndTime)
	var i UpdateTimeSlotTemplateItemRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}
